apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-website-deployment
spec:
  replicas: 1  # Only one instance for low traffic
  selector:
    matchLabels:
      app: my-website
  template:
    metadata:
      labels:
        app: my-website
    spec:
      containers:
      - name: my-website
        image: gcr.io/cultivated-card-432214-m8/appimage  # Correct image name
        ports:
        - containerPort: 5000  # Adjust if your app listens on a different port
        resources:
          requests:
            cpu: "50m"  # Low CPU request for minimal traffic
            memory: "128Mi"  # Low memory request for a basic website
          limits:
            cpu: "200m"  # Set a reasonable CPU limit for potential spikes
            memory: "256Mi"  # Set a reasonable memory limit for potential spikes